[package]
name = "cleanrs"
version = "0.1.6"
edition = "2021"
description = "Safe, rule-based disk cleanup for macOS and Windows"
homepage = "https://github.com/ho-doan/my-cleaner"
repository = "https://github.com/ho-doan/my-cleaner"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cleanrs-core = { path = "../cleanrs-core" }
cleanrs-tui = { path = "../cleanrs-tui" }
comfy-table = "7"
humansize = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[[bin]]
name = "cleanrs"
path = "src/main.rs"
